paths:
  raw_data: 
    folder: "data/raw/"
    file: "heart_disease_dataset.csv"
  processed_data: 
    folder: "data/processed/"
    file: "clean.csv"
  database_path:
    folder: "data/"
    file: "clinflow.db"

target_column_name: "num"
missing_value_strategy: "drop"
categorical_column_names: ["sex", "cp", "restecg", "thal"]
numerical_column_names: ["age", "trestbps", "chol", "fbs", "thalach", "ca", "num",]
raw_all_column_names: ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "num"]
clean_all_column_names: ["age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach", "exang", "oldpeak", "slope", "ca", "thal", "num", "target"]

reasonable_ranges:
  age:
    min: 0
    max: 120
  chol:
    min: 60
    max: 600
  thalach:
    min: 30
    max: 300
  trestbps:
    min: 30
    max: 300

minimum_rows: 50

# for train.py
model_training:
  target_column_name: "target"
  exclude_columns: ["target", "num"]    # remaining are features
  numerical_features: ["age", "trestbps", "chol", "fbs", "thalach", "ca"]  # Explicit
  categorical_features: ["sex", "cp", "restecg", "thal"]
  test_size: 0.2
  random_state: 42
  model_params:
    max_iter: 1000
    C: 1.0
    solver: "lbfgs"
  path_to_results: 
    directory: "results/"
    file: "metrics.json"